name: 'Terraform_Plan'

on:
  pull_request:
    branches: [master]

permissions:
  pull-requests: write

jobs:
  terraform_plan:
    name: 'terraform_plan'
    runs-on: runner-1
    
    defaults:
      run:
        shell: bash
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup GCP CLI
      if: success()
      run: |
        echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV

    - name: Terraform Init
      if: success()
      run: |
        echo $GOOGLE_APPLICATION_CREDENTIALS
        terraform init

    - name: Terraform Plan
      if: success()
      id: plan
      run: terraform plan --var-file=values.tfvars
      continue-on-error: true

    - name: Post Terraform Plan as PR Comment
      if: success()
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          ### Terraform Plan Output
          ```
          ${{ steps.plan.outputs.stdout || 'Terraform plan failed or had no changes.' }}
          ```
