name: 'Terraform Apply'

on:
  push:
    branches: [master]

permissions:
  pull-requests: write

jobs:
  terraform-apply:
    runs-on: runner-1

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup gcp credentials
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV

      - name: terraform init
        run: terraform init

      - name: terraform apply
        run: terraform apply --auto-approve --var-file=values.tfvars
    
